### ISSUE TITLE
Tests fail with ubuntu version strings

### ISSUE THREAD

**Issue by bryceharrington** [jelmer/debmutate#1]
In ubuntu we had pulled in a cherrypicked fix and so were publishing debmutate with a ubuntu-specific version number.  Unfortunately this confuses debmutate's tests, resulting in these test failures:

======================================================================
FAIL: test_matches_package_version (debmutate.tests.test_debmutate.DebmutateVersion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bryce/pkg/Debmutate/ubuntu-jammy/debmutate-0.45ubuntu3/debmutate/tests/test_debmutate.py", line 42, in test_matches_package_version
    self.assertEqual(cl_version, version_string)
AssertionError: '0.45ubuntu3' != '0.45'
- 0.45ubuntu3
+ 0.45

======================================================================
FAIL: test_matches_setup_version (debmutate.tests.test_debmutate.DebmutateVersion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bryce/pkg/Debmutate/ubuntu-jammy/debmutate-0.45ubuntu3/debmutate/tests/test_debmutate.py", line 57, in test_matches_setup_version
    self.assertEqual(version_string, setup_version)
AssertionError: '0.45' != '0.45ubuntu2'
- 0.45
+ 0.45ubuntu2

The workaround I've applied just splits the version on "ubuntu", which works but there's probably a better way to fix it.  Maybe it'd be better to use a sample data file rather than the 'live' debian/changelog?

**Comment by jelmer** [comment]
The point of this test is to verify that Python version number matches that of the packaging (i.e. debian/changelog), since this is a native package. Using a sample data file would defeat the purpose :)

In this case, I think I would expect Ubuntu to patch setup.py and debmutate/__init__.py to update the version number. Maybe just stripping the ubuntuX suffix is reasonable, assuming Ubuntu isn't going to significantly diverge from upstream?

**Comment by bryceharrington** [comment]
Hi Jelmer, thanks for the quick response.  

Indeed, I've patched the test cases in Ubuntu to strip the ubuntuX suffix, but your assumption is correct that our intention would be to ship debmutate without any divergence at all on our end, as that lets us update the most efficiently.

I notice that versions.py and changelog.py include provisions for handling Kali and Ubuntu version numbers, so it seems to me it would not go against debmutate's design intention to also be buildable on Debian-derivatives?  Since the Debian build system requires a successful pass of the testsuite for a successful build, it would seem that having the upstream testsuite run successfully on Debian-derivitives would be in-scope for the project?

version.new_upstream_package_version() implements functionality to append "-0ubuntu1" to an upstream version string.  Perhaps it would be logical to add a corresponding routine that strips the ubuntuX from a given version string?  The test cases could then use that routine to de-distroize the changelog version number for validation.

**Comment by jelmer** [comment]
The intent is to support building on other distributions.However, what I do when I add a new changelog entry in Debian is to update `setup.py` and `debmutate/__init__.py` with the new version - I'd expect the same to happen in Ubuntu and Kali whenever they add changelog entries rather than importing the package as-is.

**Comment by jelmer** [comment]
Closing this; see also https://salsa.debian.org/jelmer/debmutate/-/merge_requests/7 for further discussion
